package com.baoluo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT_DB.
 */
public class ContactDb {

    private Long id;
    private String myId;
    private String userId;
    private String userName;
    private String remarkName;
    private String avatar;
    private Integer dnded;

    public ContactDb() {
    }

    public ContactDb(Long id) {
        this.id = id;
    }

    public ContactDb(Long id, String myId, String userId, String userName, String remarkName, String avatar, Integer dnded) {
        this.id = id;
        this.myId = myId;
        this.userId = userId;
        this.userName = userName;
        this.remarkName = remarkName;
        this.avatar = avatar;
        this.dnded = dnded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getRemarkName() {
        return remarkName;
    }

    public void setRemarkName(String remarkName) {
        this.remarkName = remarkName;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getDnded() {
        return dnded;
    }

    public void setDnded(Integer dnded) {
        this.dnded = dnded;
    }

}
