package com.baoluo.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgDbDaoConfig;
    private final DaoConfig contactDbDaoConfig;
    private final DaoConfig groupDbDaoConfig;
    private final DaoConfig messageDbDaoConfig;

    private final MsgDbDao msgDbDao;
    private final ContactDbDao contactDbDao;
    private final GroupDbDao groupDbDao;
    private final MessageDbDao messageDbDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgDbDaoConfig = daoConfigMap.get(MsgDbDao.class).clone();
        msgDbDaoConfig.initIdentityScope(type);

        contactDbDaoConfig = daoConfigMap.get(ContactDbDao.class).clone();
        contactDbDaoConfig.initIdentityScope(type);

        groupDbDaoConfig = daoConfigMap.get(GroupDbDao.class).clone();
        groupDbDaoConfig.initIdentityScope(type);

        messageDbDaoConfig = daoConfigMap.get(MessageDbDao.class).clone();
        messageDbDaoConfig.initIdentityScope(type);

        msgDbDao = new MsgDbDao(msgDbDaoConfig, this);
        contactDbDao = new ContactDbDao(contactDbDaoConfig, this);
        groupDbDao = new GroupDbDao(groupDbDaoConfig, this);
        messageDbDao = new MessageDbDao(messageDbDaoConfig, this);

        registerDao(MsgDb.class, msgDbDao);
        registerDao(ContactDb.class, contactDbDao);
        registerDao(GroupDb.class, groupDbDao);
        registerDao(MessageDb.class, messageDbDao);
    }
    
    public void clear() {
        msgDbDaoConfig.getIdentityScope().clear();
        contactDbDaoConfig.getIdentityScope().clear();
        groupDbDaoConfig.getIdentityScope().clear();
        messageDbDaoConfig.getIdentityScope().clear();
    }

    public MsgDbDao getMsgDbDao() {
        return msgDbDao;
    }

    public ContactDbDao getContactDbDao() {
        return contactDbDao;
    }

    public GroupDbDao getGroupDbDao() {
        return groupDbDao;
    }

    public MessageDbDao getMessageDbDao() {
        return messageDbDao;
    }

}
