package com.baoluo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP_DB.
 */
public class GroupDb {

    private Long id;
    private String myId;
    private Integer groupType;
    private String groupId;
    private String groupName;
    private String groupAvatar;
    private String describe;
    private String owner;
    private Integer dnded;

    public GroupDb() {
    }

    public GroupDb(Long id) {
        this.id = id;
    }

    public GroupDb(Long id, String myId, Integer groupType, String groupId, String groupName, String groupAvatar, String describe, String owner, Integer dnded) {
        this.id = id;
        this.myId = myId;
        this.groupType = groupType;
        this.groupId = groupId;
        this.groupName = groupName;
        this.groupAvatar = groupAvatar;
        this.describe = describe;
        this.owner = owner;
        this.dnded = dnded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    public Integer getGroupType() {
        return groupType;
    }

    public void setGroupType(Integer groupType) {
        this.groupType = groupType;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getGroupAvatar() {
        return groupAvatar;
    }

    public void setGroupAvatar(String groupAvatar) {
        this.groupAvatar = groupAvatar;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public Integer getDnded() {
        return dnded;
    }

    public void setDnded(Integer dnded) {
        this.dnded = dnded;
    }

}
