package com.baoluo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_DB.
 */
public class MessageDb {

    private Long id;
    private String myId;
    private String toId;
    private Integer msgType;
    private java.util.Date iTime;
    private java.util.Date setTopTime;

    public MessageDb() {
    }

    public MessageDb(Long id) {
        this.id = id;
    }

    public MessageDb(Long id, String myId, String toId, Integer msgType, java.util.Date iTime, java.util.Date setTopTime) {
        this.id = id;
        this.myId = myId;
        this.toId = toId;
        this.msgType = msgType;
        this.iTime = iTime;
        this.setTopTime = setTopTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    public String getToId() {
        return toId;
    }

    public void setToId(String toId) {
        this.toId = toId;
    }

    public Integer getMsgType() {
        return msgType;
    }

    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    public java.util.Date getITime() {
        return iTime;
    }

    public void setITime(java.util.Date iTime) {
        this.iTime = iTime;
    }

    public java.util.Date getSetTopTime() {
        return setTopTime;
    }

    public void setSetTopTime(java.util.Date setTopTime) {
        this.setTopTime = setTopTime;
    }

}
