package com.baoluo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MSG_DB.
 */
public class MsgDb {

    private Long id;
    /** Not-null value. */
    private String myId;
    private String fromId;
    /** Not-null value. */
    private String toId;
    private Integer isOut;
    private Integer msgType;
    private Integer contentType;
    private java.util.Date itime;
    private String body;
    private Integer isRead;
    private Integer showTimed;

    public MsgDb() {
    }

    public MsgDb(Long id) {
        this.id = id;
    }

    public MsgDb(Long id, String myId, String fromId, String toId, Integer isOut, Integer msgType, Integer contentType, java.util.Date itime, String body, Integer isRead, Integer showTimed) {
        this.id = id;
        this.myId = myId;
        this.fromId = fromId;
        this.toId = toId;
        this.isOut = isOut;
        this.msgType = msgType;
        this.contentType = contentType;
        this.itime = itime;
        this.body = body;
        this.isRead = isRead;
        this.showTimed = showTimed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMyId() {
        return myId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMyId(String myId) {
        this.myId = myId;
    }

    public String getFromId() {
        return fromId;
    }

    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /** Not-null value. */
    public String getToId() {
        return toId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToId(String toId) {
        this.toId = toId;
    }

    public Integer getIsOut() {
        return isOut;
    }

    public void setIsOut(Integer isOut) {
        this.isOut = isOut;
    }

    public Integer getMsgType() {
        return msgType;
    }

    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    public Integer getContentType() {
        return contentType;
    }

    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    public java.util.Date getItime() {
        return itime;
    }

    public void setItime(java.util.Date itime) {
        this.itime = itime;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public Integer getIsRead() {
        return isRead;
    }

    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    public Integer getShowTimed() {
        return showTimed;
    }

    public void setShowTimed(Integer showTimed) {
        this.showTimed = showTimed;
    }

}
